---
  - name: delete all instances
    os_server:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ project_name }}"
         password: "{{ project_password }}"
         project_name: "{{ project_name }}"
         domain_id: "{{ domain_id }}"
       state: "{{ state }}"
       name: "{{ item.id }}"
       validate_certs: False
    with_items: "{{ openstack_instances.ansible_facts.openstack_servers }}"
