---
- name: verify instance is up and reachable
  command: >
    ssh -o BatchMode=yes -o StrictHostKeyChecking=no
    {{cloud_user}}@{{instance.openstack.accessIPv4}} true
  register: result
  until: result|success
  retries: 30
  delay: 10
